// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <bigmemory/MatrixAccessor.hpp>

using namespace Rcpp;

// countExBM
void countExBM(SEXP mat_reads, SEXP regid_, SEXP exnames_, SEXP colID_, XPtr<BigMatrix> pBigMat);
RcppExport SEXP Sequgio_countExBM(SEXP mat_readsSEXP, SEXP regid_SEXP, SEXP exnames_SEXP, SEXP colID_SEXP, SEXP pBigMatSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type mat_reads(mat_readsSEXP );
        Rcpp::traits::input_parameter< SEXP >::type regid_(regid_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type exnames_(exnames_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type colID_(colID_SEXP );
        Rcpp::traits::input_parameter< XPtr<BigMatrix> >::type pBigMat(pBigMatSEXP );
        countExBM(mat_reads, regid_, exnames_, colID_, pBigMat);
    }
    return R_NilValue;
END_RCPP
}
// makeExNames
SEXP makeExNames(SEXP txdb_, SEXP reg_id_);
RcppExport SEXP Sequgio_makeExNames(SEXP txdb_SEXP, SEXP reg_id_SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type txdb_(txdb_SEXP );
        Rcpp::traits::input_parameter< SEXP >::type reg_id_(reg_id_SEXP );
        SEXP __result = makeExNames(txdb_, reg_id_);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
