// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP Sequgio_countExBM(SEXP mat_readsSEXP, SEXP regid_SEXP, SEXP exnames_SEXP, SEXP colID_SEXP, SEXP pBigMatSEXP);
SEXP Sequgio_makeExNames(SEXP txdb_SEXP, SEXP reg_id_SEXP);

R_CallMethodDef callMethods[]  = {
  {"Sequgio_countExBM", (DL_FUNC) &Sequgio_countExBM, 5},
  {"Sequgio_makeExNames", (DL_FUNC) &Sequgio_makeExNames, 2},
  {NULL, NULL, 0}
};

void R_init_Sequgio(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

