# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countExBM <- function(mat_reads, regid_, exnames_, colID_, pBigMat) {
    invisible(.Call('Sequgio_countExBM', PACKAGE = 'Sequgio', mat_reads, regid_, exnames_, colID_, pBigMat))
}

